# -*- coding: utf-8 -*-

from . import patient
from . import appointment
from . import patient_tag
from . import appointment_line
from . import account_move
from . import ir_attachment
from . import contract_indication
from . import hr_employee
from . import blood_bank
from . import blood_donation
from . import hospital_insurance
from . import doctor_allocation
from . import doctor_slot
from . import inpatient_surgery
from . import hospital_vaccination
from . import inpatient_payment
from . import doctor_round
from . import lab_test_result
from . import lab_test
from . import lab_test_line
from . import lab_medicine_line
from . import patients_room
from . import hospital_bed
from . import hoapital_ward
from . import hospital_degree
from . import hospital_laboratory
from . import hospital_pharmacy
from . import doctor_specialization
from . import hospital_inpatient
from . import hospital_outpatient
from . import product_template
from . import hospital_building
from . import room_facility
from . import medicine_brand
from . import nursing_plan
from . import patient_lab_test
from . import pharmacy_medicine
from . import prescription_line
from . import product_template