[options]
db_host = localhost
db_port = 5432
db_user = odoo17
db_password = admin
;db_name = odoo17db
dbfilter= odoo17db_hospital_management
addons_path = /home/komsonit/CommunityPath/odoo/addons,
	/home/komsonit/CommunityPath/odoo/custom_addons, partner-contact
default_productivity_apps = True
xmlrpc_port = 8069
xmlrpc_interface = 0.0.0.0
netrpc_interface = 0.0.0.0


